In [1]:
import numpy as np
import json

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

def loadMatrices(filename):
    with open(filename) as f:
        result = json.load(f)
    for key, value in result.items():
        result[key] = np.array(value).reshape(4, 4)
    return result


In [2]:
misMat=loadMatrices("../../output/misMat-modules.json")
externalMats=loadMatrices("../../output/externalMatrices-modules.json")

with open('../../input/sectorPaths.json') as f:
    sectorPaths = json.load(f)

In [5]:
for i in range(10):
    print(f" ------------ sector {i} ------------")
    print('external matrix:')
    print(f'{externalMats[str(i)]*1e4}')

    avgMat = np.eye(4)

    for path in sectorPaths[str(i)]:
        avgMat = avgMat @ misMat[path]

    print('avg misalign matrix:')
    print(f'{avgMat*1e4/4}')



 ------------ sector 0 ------------
external matrix:
[[ 9999.999811     1.943161     0.         -11.222354]
 [   -1.943161  9999.999811     0.          90.990451]
 [    0.           0.       10000.           0.      ]
 [    0.           0.           0.       10000.      ]]
avg misalign matrix:
[[2499.999245    1.943161    0.        -11.186731]
 [  -1.943161 2499.999245    0.         91.062599]
 [   0.          0.       2500.          0.      ]
 [   0.          0.          0.       2500.      ]]
 ------------ sector 1 ------------
external matrix:
[[ 9999.985313    17.139097     0.          58.174512]
 [  -17.139097  9999.985313     0.         -53.76356 ]
 [    0.           0.       10000.           0.      ]
 [    0.           0.           0.       10000.      ]]
avg misalign matrix:
[[2499.94125    17.138972    0.         57.990489]
 [ -17.138972 2499.94125     0.        -54.001015]
 [   0.          0.       2500.          0.      ]
 [   0.          0.          0.       2500.      ]]
