In [1]:
import numpy as np
import sys
sys.path.append("../")
from src.util.matrix import loadMatrices

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

# Compare Box Rotation Euler Angles

In [2]:
def rotationMatrixToEulerAngles(R):

    assert R.shape == (4, 4) or R.shape == (3, 3)

    sy = np.sqrt(R[0, 0] * R[0, 0] + R[1, 0] * R[1, 0])
    singular = sy < 1e-6

    if not singular:
        x = np.arctan2(R[2, 1], R[2, 2])
        y = np.arctan2(-R[2, 0], sy)
        z = np.arctan2(R[1, 0], R[0, 0])
    else:
        x = np.arctan2(-R[1, 2], R[1, 1])
        y = np.arctan2(-R[2, 0], sy)
        z = 0

    return np.array([x, y, z])

In [7]:
# open the actual misalignment matrix
misMatBox = loadMatrices("../matrices/100u-case-1/misMat-box.json")['/cave_1/lmd_root_0']

# open 1.5GeV alignment matrix
alMatExample = loadMatrices("../matrices/100u-case-1/EXAMPLE-boxAlignMatrix.json")['/cave_1/lmd_root_0']
alMat1_5 = loadMatrices("../matrices/100u-case-1/boxAlignmentMatricees-1.5.json")['/cave_1/lmd_root_0']
alMat15 = loadMatrices('../matrices/100u-case-1/boxAlignmentMatricees-15.json')['/cave_1/lmd_root_0']

print("Actual Misalgiment Matrix:")
print(rotationMatrixToEulerAngles(misMatBox)*1e3)

# print residuals matrices
print('Euler Angles example case:')
print(rotationMatrixToEulerAngles(alMatExample)*1e3)

# print('Euler Angles 1.5:')
# print(rotationMatrixToEulerAngles((misMatBox @ alMat1_5)*1e6))
# print(rotationMatrixToEulerAngles(alMat1_5)*1e3)

# print('Euler Angles 15:')
# print(rotationMatrixToEulerAngles((misMatBox @ alMat15)*1e6))
# print(rotationMatrixToEulerAngles(alMat15)*1e3)


Actual Misalgiment Matrix:
[-0.55573   1.965781  1.393406]
Euler Angles example case:
[-0.489442  1.92238  -0.008862]


# Compare Sensor Misalignment Matrices

In [4]:
# alignmentMatrixFilename = '../matrices/100u-case-1/sensorAlignmentMatrices-15.json'
alignmentMatrixFilename = '../matrices/100u-case-1/EXAMPLE-sensorAlignmentMatrices.json'

paths = []

for iHalf in range(2):
    for iPlane in range(4):
        for iModule in range(5):
            for iSensor in range(8):
                paths.append(f'/cave_1/lmd_root_0/half_{iHalf}/plane_{iPlane}/module_{iModule}/sensor_{iSensor}')

# oldAnchorMatrices = loadMatrices('../../output/alMat-modules-oldAnchors.json')
newAnchorMatrices = loadMatrices(alignmentMatrixFilename)
mActual = loadMatrices('../matrices/100u-case-1/misMat-sensors.json')

for path in paths:

    print('--------------------------------------------------------:')
    print('Path: ' + path)
    print('Residuals Matrix:\n')
    print((np.linalg.inv(newAnchorMatrices[path]) @ mActual[path])*1e4)

--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_0/sensor_0
Residuals Matrix:

[[10000.     0.     0.     0.]
 [   -0. 10000.     0.     0.]
 [    0.     0. 10000.     0.]
 [    0.     0.     0. 10000.]]
--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_0/sensor_1
Residuals Matrix:

[[10000.     0.     0.    -0.]
 [    0. 10000.     0.     0.]
 [    0.     0. 10000.     0.]
 [    0.     0.     0. 10000.]]
--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_0/sensor_2
Residuals Matrix:

[[ 9999.998598    -5.295097    -0.          -2.073627]
 [    5.295097  9999.998598    -0.          -4.960483]
 [    0.           0.       10000.           0.      ]
 [    0.           0.           0.       10000.      ]]
--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_0/sensor_3
Residual

# Compare Module Misalignment Matrices

In [5]:
# alignmentMatrixFilename = '../matrices/100u-case-1/moduleAlignmentMatrices-15.00.json'
alignmentMatrixFilename = '../matrices/100u-case-1/EXAMPLE-moduleAlignmentMatrices.json'

paths = []

for iHalf in range(2):
    for iPlane in range(4):
        for iModule in range(5):
            paths.append(f'/cave_1/lmd_root_0/half_{iHalf}/plane_{iPlane}/module_{iModule}')

# oldAnchorMatrices = loadMatrices('../../output/alMat-modules-oldAnchors.json')
newAnchorMatrices = loadMatrices(alignmentMatrixFilename)
mActual = loadMatrices('../matrices/100u-case-1/misMat-modules.json')

for path in paths:

    print('--------------------------------------------------------:')
    print('Path: ' + path)
    print('Residuals Matrix:\n')
    print((np.linalg.inv(newAnchorMatrices[path]) @ mActual[path])*1e4)

--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_0
Residuals Matrix:

[[ 9999.999998     0.201359     0.           2.119288]
 [   -0.201359  9999.999998    -0.          -4.983797]
 [    0.           0.       10000.          -0.      ]
 [    0.           0.           0.       10000.      ]]
--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_1
Residuals Matrix:

[[ 9999.999995    -0.307878    -0.          -2.283598]
 [    0.307878  9999.999995     0.           3.443389]
 [   -0.           0.       10000.           0.      ]
 [    0.           0.           0.       10000.      ]]
--------------------------------------------------------:
Path: /cave_1/lmd_root_0/half_0/plane_0/module_2
Residuals Matrix:

[[10000.          -0.050705     0.          -0.997921]
 [    0.050705 10000.          -0.           8.735286]
 [   -0.           0.       10000.           0.      ]
 [    0.       